language: php
php:
  - '7.0'
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.composer/cache  
notifications:
  email:
    - manaphp@qq.com
script:
# flags to pass to install
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  # install dependencies using system provided composer binary
  - composer install $flags
  - cp .env.example .env
  - composer archive -f zip --file release
before_deploy:
      - git config --local user.name "Mark"
      - git config --local user.email "manaphp@qq.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-v1.$(date +'%y%m%d').$(date +'%H%M%S')}
      - git tag $TRAVIS_TAG --force
      - env
      - export RELEASE_NAME=${TRAVIS_REPO_SLUG/\//_}_$TRAVIS_TAG.zip
      - mv release.zip $RELEASE_NAME
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
  overwrite: true
  api_key: $GITHUB_TOKEN
  file: 
   - $RELEASE_NAME
  skip_cleanup: true
  on:
    branch: master
