version: "2"
services:
  api:
    image: manaphp/php74:3.1
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/api/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/api/tmp:/var/www/html/tmp
    command: php /var/www/html/public/index.php
    ports:
      - ${WEB_PORT}:9501
    restart: always